export const requestStatuses = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  AWAITING_MORE_INFORMATION: 'AWAITING_MORE_INFORMATION',
  AWAITING_CALL_BACK: 'AWAITING_CALL_BACK',
  APPOINTMENT_PROPOSED: 'APPOINTMENT_PROPOSED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  DECLINED: 'DECLINED',
  REFERRED_ELSEWHERE: 'REFERRED_ELSEWHERE',
  CANCELLED: 'CANCELLED',
};

export const requestCategories = {
  NEW_ENQUIRY: 'NEW_ENQUIRY',
  FOLLOW_UP: 'FOLLOW_UP',
  URGENT: 'URGENT',
  ROUTINE: 'ROUTINE',
  NOT_SUITABLE: 'NOT_SUITABLE',
};

export const requestActions = {
  ASK_FOR_MORE_INFORMATION: 'ASK_FOR_MORE_INFORMATION',
  CALL_PATIENT: 'CALL_PATIENT',
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  DECLINE_OR_REFER: 'DECLINE_OR_REFER',
};

export const statusTransitions = {
  SUBMITTED: ['UNDER_REVIEW', 'DECLINED', 'REFERRED_ELSEWHERE', 'CANCELLED'],
  UNDER_REVIEW: [
    'AWAITING_MORE_INFORMATION',
    'AWAITING_CALL_BACK',
    'APPOINTMENT_PROPOSED',
    'PAYMENT_PENDING',
    'DECLINED',
    'REFERRED_ELSEWHERE',
    'CANCELLED',
  ],
  AWAITING_MORE_INFORMATION: ['UNDER_REVIEW', 'AWAITING_CALL_BACK', 'CANCELLED'],
  AWAITING_CALL_BACK: ['UNDER_REVIEW', 'APPOINTMENT_PROPOSED', 'CANCELLED'],
  APPOINTMENT_PROPOSED: ['PAYMENT_PENDING', 'CONFIRMED', 'CANCELLED'],
  PAYMENT_PENDING: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['CANCELLED'],
  DECLINED: [],
  REFERRED_ELSEWHERE: [],
  CANCELLED: [],
};

export function canTransition(fromStatus, toStatus) {
  if (fromStatus === toStatus) return true;
  return Boolean(statusTransitions[fromStatus]?.includes(toStatus));
}
